# MariaDB 이미지를 기본으로 사용
FROM mariadb:latest

# 시스템 패키지 업데이트 및 Python 설치
RUN apt-get update && apt-get install -y python3 python3-pip

# 필요 패키지 설치 (가상환경 없이 시스템에 직접 설치)
RUN pip3 install --upgrade pip
RUN pip3 install beautifulsoup4 fredapi pykrx yfinance pymysql==1.1.1 faker

# 데이터베이스 초기화 스크립트 복사
COPY DB_setting.py /docker-entrypoint-initdb.d/
COPY database_id.txt /docker-entrypoint-initdb.d/
COPY init.sql /docker-entrypoint-initdb.d/

# 포트 설정
EXPOSE 3306
